name: Unzip Android Folder

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip android.zip
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          unzip android.zip -d .
      
      - name: Commit extracted android folder
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add android
          git commit -m "Unzipped android folder"
          git push
